name: create

on:
  workflow_dispatch:
    inputs:
      includes_folder:
        description: 'Copy .conf too'     
        required: true
        default: 'includes'
      pr_branch:
        description: 'Branch to push changes to'     
        required: true
        default: 'github-actions-runners'        

  # push:
  #   branches:
  #     - '*'
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: SETUP .NET CORE
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: INSTALL DEPENDENCIES
      run: dotnet restore
    - name: BUILD
      run: dotnet build -c Release --no-restore -o app/build
    - name: TEST
      run: dotnet test --no-restore --verbosity normal
    - name: PUBLISH
      run: |
        pushd ''
        dotnet publish -c Release -o app/publish -r linux-x64
        popd
    - name: RUN
      run: |
        dotnet app/publish/AllowList.dll
        cat output/github-actions-runners.conf        
    - name: COPY      
      run: |
        mkdir -p '${{ github.event.inputs.includes_folder }}'
        cp output/github-actions-runners.conf '${{ github.event.inputs.includes_folder }}/'
    - name: COMMIT FILE
      run: |
        git config --local user.email "garrardkitchen@gmail.com"
        git config --local user.name "Garrard Kitchen"
        git checkout -b ${{ github.event.inputs.pr_branch }}
        git add '${{ github.event.inputs.includes_folder }}/github-actions-runners.conf'        
        git commit -m "chore(cicd): added updated runners"
        git pull origin ${{ github.event.inputs.pr_branch }}
    - name: PUSH
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.event.inputs.pr_branch }}
    - name: CREATE PR
      id: cpr
      uses: peter-evans/create-pull-request@v2
      with:
        title: "Update GitHub Actions Runners list"
        branch: ${{ github.event.inputs.pr_branch }}
        
