name: create

on:
  push:
    branches:
      - '*'
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: SETUP .NET CORE
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: INSTALL DEPENDENCIES
      run: dotnet restore
    - name: BUILD
      run: dotnet build -c Release --no-restore -o app/build
    - name: TEST
      run: dotnet test --no-restore --verbosity normal
    - name: PUBLISH
      run: |
        pushd ''
        dotnet build -c Release -o app/publish -r linux-x64
        popd
    - name: RUN
      run: |
        dotnet run app/publish/AllowList.dll
        cat output/github-actions-runners.conf        
    - name: COPY
      run: COPY output/github-actions-runners.conf includes/
    - name: COMMIT FILE
      run: |
        git config --local user.email "garrardkitchen@gmail.com"
        git config --local user.name "Garrard Kitchen"
        git add includes/github-actions-runners.conf
        git commit -m "chore(cicd): added updated runners"
    - name: PUSH
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: CREATE PR
      id: cpr
      uses: peter-evans/create-pull-request@v2
      with:
        title: "Update GitHub Actions Runners list"
        
